---
apiVersion: v1
kind: Namespace
metadata:
  name: elevatormaintenance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elevatormaintenance
  labels:
    name: elevatormaintenance
  namespace: elevatormaintenance
spec:
  replicas: 1
  selector:
    matchLabels:
      name: elevatormaintenance
  template:
    metadata:
      labels:
        name: elevatormaintenance
    spec:
      containers:
      - name: elevatormaintenance
        image: venkatelevatormaintenance:1.0-SNAPSHOT
        imagePullPolicy: Never        
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: elevatormaintenance
  annotations:
        #prometheus.io/scrape: 'true'
  labels:
    name: elevatormaintenance
  namespace: elevatormaintenance
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: elevatormaintenance
---